[TOC]

# 异常处理

## 处理异常

```python
def exe_try():
    try:
        # 初始执行代码
        print('code start')
        raise KeyError
        return 1  # 有return，无异常则不执行else代码块
    except KeyError as e:
        # 异常时执行代码
        print('key error')
        return 2
    else:
        # 无异常时执行代码
        print('other error')
        return 3
    finally:
        # 无论有无异常均执行代码
        print('finally')
        return 4  # 有return，则优先执此处而不执行上方代码块的return；无return，执行上面代码块的return

if __name__ == "__main__":
    res = exe_try()
    print(res)
```

多个except子句
```python
# 一个try语句可能包含多个except子句，分别来处理不同的特定的异常。最多只有一个分支会被执行。
try:
	pass
except Error1 as e:
    pass
except Error2 as e:
    pass
```
一个except子句，多个异常类型
```python
一个块同时捕捉多个异常类型，执行同一个操作
try:
	pass
except Exception as e:
    pass
```
try-except嵌套
```python
如果一个异常没有与任何的except匹配，那么这个异常将会传递给上层的try中
try:
	pass
    try:
        pass
    except Error1 as e:
        pass
except Exception as e:
    pass
```
函数嵌套中的异常
```
异常处理并不仅仅处理那些直接发生在try子句中的异常，而且还能处理子句中调用的函数（甚至间接调用的函数）里抛出的异常
```
## 抛出异常

```python
# 若是只想知道是否抛出了一个异常，并不处理它，可用raise
# 格式：raise 被抛出的异常
# 要被抛出的异常必须是一个异常的实例或者是异常的类（也就是 Exception 的子类）。
raise NameError('HiThere')

raise Exception("logError")
```

## 常见异常

| 异常名称    | 描述             | 异常名称       | 描述               |
| ----------- | ---------------- | -------------- | ------------------ |
| Exception   | 常规错误的基类   | AttributeError | 对象无此属性       |
| IOError     | 输入输出操作失败 | IndexError     | 序列中没此索引     |
| KeyError    | 映射中没有此键   | NameError      | 未声明对象         |
| SyntaxError | 语法错误         | SystemError    | 一般解释器系统错误 |
| ValueError  | 传入无效参数     |                |                    |

```python
try
	...
except Exception as e:
	....

str(e)
# 返回字符串类型，只给出异常信息，不包括异常信息的类型如1/0的异常信息
#'integer division or modulo by zero' 
repr(e)
# 给出较全的异常信息，包括异常信息的类型，如1/0的异常信息
# "ZeroDivisionError('integer division or modulo by zero',)"
e.message
# 获得的信息同str(e)
```

## 自定义异常

```python
# 通过创建一个新的exception类来拥有自己的异常。异常应该继承自 Exception 类，或者直接继承，或者间接继承  
class MyError(Exception):
        def __init__(self, value):
            self.value = value
        def __str__(self):
            return repr(self.value)
            
# 抛出异常信息            
raise MyError('oops!')  

# 调用自定义异常          
try:
    raise MyError(2*2)
except MyError as e:
    print('My exception occurred, value:', e.value)
```
# 调试

## print

```python
def foo(s):
    n = int(s)
    print('>>> n = %d' % n)
    return 10 / n

def main():
    foo('0')

main()
```

## 断言

凡是用`print()`来辅助查看的地方，都可以用断言（assert）来替代：如果断言失败，`assert`语句本身就会抛出`AssertionError`;启动Python解释器时可以用`-O`参数来关闭`assert`：

```
def foo(s):
    n = int(s)
    assert n != 0, 'n is zero!'
    return 10 / n

def main():
    foo('0')
```

## traceback

traceback可以提示报错行

```python
import traceback

try:
    1/0
except Exception, e:
    traceback.print_exc()
```

使用traceback.print_exc()打印异常信息到标准错误，就像没有获取一样

使用traceback.format_exc()将同样的输出获取为字符串。

你可以向这些函数传递各种各样的参数来限制输出，或者重新打印到像文件类型的对象。

## logging

`logging`不会抛出错误，而且可以输出到文件；允许你指定记录信息的级别，有`debug`，`info`，`warning`，`error`等几个级别

```
import logging

logging.basicConfig(level=logging.INFO)
s = '0'
n = int(s)
logging.info('n = %d' % n)
print(10 / n)
```

## pdb

pdb是python自带的交互式源代码调试模块，源文件是pdb.py，可以在python安装目录中查看。

提供了代码调试的绝大部分功能，包括设置/清除断点、启用/禁用断点、单步执行、查看栈帧、查看变量值、查看当前执行位置、列出源代码、执行任意python代码或表达式等。还支持事后调试，可在程序控制下被调用，并可以通过pdb或cmd接口对该调试器进行扩展

常用调试命令

| 命令                                             | 示例                 | 说明                                                         |
| ------------------------------------------------ | -------------------- | ------------------------------------------------------------ |
| a(rgs)                                           |                      | 显示当前函数中的参数                                         |
| b(reak)[[filename:]lineno\|function[,condition]] | b 173                | 在173行设置断点                                              |
|                                                  | b function           | 在function函数第一条可执行语句位置设置断点                   |
|                                                  | b                    | 不带参数则累出所有断点，包括每个断点的触发次数、当前忽略计数以及与之关联的条件 |
|                                                  | b 175, condition     | 设置条件断点，仅当condition的值为True时该断点有效            |
| cl(ear)[filename:lineno\|bpnumber[bpnumber...]]  | cl                   | 清除所有断点                                                 |
|                                                  | cl file:line         | 删除指定文件中指定行的所有断点                               |
|                                                  | cl 3 5 9             | 删除第3、5、9个断点                                          |
| condition bpnumber[condition]                    | condition    3 a < b | 仅当a<b时3号断点有效                                         |
|                                                  | Condition 3          | 将3号断点设置为无条件断点                                    |
| c(ontinue)                                       |                      | 继续运行至下一个断点或脚本结束                               |
| diable[bpnumber[bpnumber...]]                    | disable 3 5          | 禁用第3、5个断点，禁用后断点仍存在们可以再次被启用           |
| d(own)                                           |                      | 在栈跟踪器中向下移动一个栈帧                                 |
| enable[bpnumber[bpnumber...]]                    | enable n             | 启用第n个断点                                                |
| h(elp) [command]                                 |                      | 查看pdb帮助                                                  |
| ignore bpnumber [count]                          |                      | 为断点设置忽略计数，count默认值为0，若某断点的忽略计数不为0，则每次触发时自动减1，当忽略计数为0时该段带你处于活动状态 |
| j(ump)                                           | j 20                 | 跳至第20行继续运行                                           |
| l(ist)[first[, last]]                            | l                    | 列出脚本清单，默认11行                                       |
|                                                  | l m, n               | 列出从第m行到第n行之间的脚本代码                             |
|                                                  | l m                  | 列出从第m行开始的11行代码                                    |
| n(ext)                                           |                      | 执行下一条语句，遇到函数时不进入其内部                       |
| p(rint)                                          | p i                  | 打印变量i的值                                                |
| q(uit)                                           |                      | 退出pdb调试环境                                              |
| r(eturn)                                         |                      | 一直运行至当前函数返回                                       |
| tbreak                                           |                      | 设置临时断点，该类型断点只被中断一次，触发后该段带你自动删除 |
| step                                             |                      | 执行下一条语句，遇到函数时进入其内部                         |
| u(p)                                             |                      | 在栈跟踪器中向上移动一个栈帧                                 |
| w(here)                                          |                      | 查看当前栈帧                                                 |
| [!]statement                                     |                      | 在pdb中执行语句，!与要执行的语句之间不需要空格，任何非pdb命令都被解释为python语句并执行，甚至可以调用函数或修改当前上下文中变量的值 |
|                                                  |                      | 直接回车则默认执行上一个命令                                 |

- 调试形式有

```
1. 在交互模式下调试特定的代码块
2. 在程序中显式插入断点
3. 把pdb作为模块来调试
```

> 交互模式

调试方法

```python
pdb.run(statement[, globals[, locals]])
# 调试指定语句，可选参数globals和locals用来指定代码执行的环境，默认是__main__模块的字典

pdb.runeval(expression[, globals[, locals]])
# 返回表达式的值，可选参数gloabls和local含义与上同

pdb.runcall(function[, argument,...])
# 调试指定函数

pdb.post_mortem([traceback])
# 进入指定traceback对象的事后调试模式，若没有指定traceback对象，则试用当前正在处理的一个异常
```

示例

```python
>>>import pdb
>>>def demo():
   from random import randint
   x = [randint(1,10) for i in range(20)]
   m = max(x)
   r = [index for index, value in enumerate(x) if value==m]
   print(r)
>>>pdb.runcall(demo)  # 调试函数
(Pdb) n  # 执行下一条语句
(Pdb) p x  # 查看变量值
(Pdb) r	 # 运行函数直至结束 
(Pdb) q  # 退出调试模式
```

> 程序中嵌入断点

也是用pdb，但是不需要单步执行，我们只需要`import pdb`，然后，在可能出错的地方放一个`pdb.set_trace()`，就可以设置一个断点

```
# err.py
import pdb

s = '0'
n = int(s)
pdb.set_trace() # 运行到这里会自动暂停
print(10 / n)
```

运行代码，程序会自动在`pdb.set_trace()`暂停并进入pdb调试环境，可以用命令`p`查看变量，或者用命令`c`继续运行

> 命令行调试

启动Python的调试器pdb，让程序以单步方式运行，可以随时查看运行状态

```
1.准备好程序
# err.py
s = '0'
n = int(s)
print(10 / n)

2.以参数-m pdb启动后，pdb定位到下一步要执行的代码-> s = '0'
python -m pdb err.py

3.输入命令l来查看代码：
(Pdb) l
  1     # err.py
  2  -> s = '0'
  3     n = int(s)
  4     print(10 / n)
  
4.输入命令n可以单步执行代码;任何时候都可以输入命令p 变量名来查看变量
(Pdb) n
(Pdb) p s

5.输入命令q结束调试，退出程序
(Pdb) q
```

## IDE

使用IDE工具调试

# 单元测试

单元测试是用来对一个模块、一个函数或者一个类来进行正确性检验的测试工作，可以在隔离环境中完成。

在进行单元测试时注意：

```
1.测试用例的设计应该是完备的，应保证覆盖尽可能多的情况，尤其要覆盖边界条件，对目标模块的功能进行充分测试，避免漏测
2.测试用例以及测试代码本身也可能存在bug，通过测试并不代表目标代码没有错误，但一般而言，不能通过测试的模块代码是存在问题的
3.再好的测试方法和测试用例也无法保证能够发现所有错误，必须通过不停改进和综合多种测试方法并精心设计测试用例来发现尽可能多的潜在问题
4.除了功能测试，还应对程序进行性能测试与安全测试，甚至要进行规范性测试以保证代码可读性和可维护性
```

单元测试框架

```
py.test
nose
unittest
```

## TeatCase类

常用方法

| 方法名                 | 说明                         | 方法名                    | 说明                           |
| ---------------------- | ---------------------------- | ------------------------- | ------------------------------ |
| assertEqual(a,b)       | a==b                         | assertNptEqual(a, b)      | a!=b                           |
| assertTrue(x)          | bool(x) is True              | assertFalse(x)            | bool(x) is False               |
| assertIs(a,b)          | a is b                       | assertIsNot(a,b)          | a is not b                     |
| assertIsNone(x)        | x is None                    | assertIsNotNone(x)        | x is not None                  |
| assertIn(a,b)          | a in b                       | assertNotIn(a,b)          | a not in b                     |
| assertIsInstance(a,b)  | isinatance(a,b)              | assertNotIsInstance(a,b)  | not isinstance(a, b)           |
| assertAlmostEqual(a,b) | round(a-b, 7)==0             | assertNotAlmostEqual(a,b) | round(a-b, 7)!=0               |
| assertGreater(a,b)     | a>b                          | assertGreaterEqual(a,b)   | a>=b                           |
| assertLess(a,b)        | a<b                          | assertLessEqual(a,b)      | a<=b                           |
| assertRegex(s,r)       | r.search(s)                  | assertNotRegex(s,r)       | not r.search(s)                |
| setUp()                | 每项测试开始前自动调用该函数 | setDown()                 | 每项测试完成之后自动调用该函数 |

> setUp/tearDown

可以在单元测试中编写两个特殊的`setUp()`和`tearDown()`方法。这两个方法会分别在每调用一个测试方法的前后分别被执行。

`setUp()`和`tearDown()`方法有什么用呢？设想你的测试需要启动一个数据库，这时，就可以在`setUp()`方法中连接数据库，在`tearDown()`方法中关闭数据库，这样，不必在每个测试方法中重复相同的代码：

```
class TestDict(unittest.TestCase):

    def setUp(self):
        print('setUp...')

    def tearDown(self):
        print('tearDown...')
```

## 编写单元测试

### 常规测试

程序代码

```python
# mydict.py

class Dict(dict):

    def __init__(self, **kw):
        super().__init__(**kw)

    def __getattr__(self, key):
        try:
            return self[key]
        except KeyError:
            raise AttributeError(r"'Dict' object has no attribute '%s'" % key)

    def __setattr__(self, key, value):
        self[key] = value
```

单元测试代码

```python
# mydict_test.py

import unittest

from mydict import Dict

class TestDict(unittest.TestCase):
		def setUp(self):
      	print('每个测试函数前准备')
    
    def tearDown(self):
      	print('每个测试函数后清理')
    
    # 测试函数需要以test_开始
    def test_init(self):
        d = Dict(a=1, b='test')
        self.assertEqual(d.a, 1)
        self.assertEqual(d.b, 'test')
        self.assertTrue(isinstance(d, dict))

    def test_key(self):
        d = Dict()
        d['key'] = 'value'
        self.assertEqual(d.key, 'value')

    def test_attr(self):
        d = Dict()
        d.key = 'value'
        self.assertTrue('key' in d)
        self.assertEqual(d['key'], 'value')

    def test_keyerror(self):
        d = Dict()
        with self.assertRaises(KeyError):
            value = d['empty']

    def test_attrerror(self):
        d = Dict()
        with self.assertRaises(AttributeError):
            value = d.empty
```

### http请求

对于单元测试中模拟http请求，有如下方案

1. 使用标准http模块(urllib2,requests)，要求被测试框架程序处于启动运行状态
2. 使用框架程序提供的单元测试客户端，程序不必处于运行状态。

```python
# flask
test_client().get()
# django
client().get()
```

### 重构代码测试

实际使用函数

```python
def calculate_age_at_wedding(person_id):
    """根据一个人的结婚日期确定其年龄"""
    # 从数据库中获取个人信息
    person = get_person_from_db(peoson_id)
    anniversary = person['anniversay']
    birthday = person['birthday']
    # 计算年龄
    age = anniversary.year - birthday.year
    # 
    if birthday.replace(year=anniversary.year) > anniversary:
        age -= 1
    return age
```

重构代码

```python
# 修正需要和外部环境交互的部分
def calculate_age_at_wedding(person):
    """根据一个人的结婚日期确定其年龄"""
    anniversary = person['anniversay']
    birthday = person['birthday']
    # 计算年龄
    age = anniversary.year - birthday.year
    # 若是生日的月份日期比周年月份日期大，则年龄减1
    if birthday.replace(year=anniversary.year) > anniversary:
        age -= 1
    return age
```

测试代码

```python
import unittest
from datetime import date

class Tests(unittest.TestCase):
    def test_calculate_age_at_wedding(self):
        # 常规测试
        person = {
            'anniversary': date(2012, 4, 21),
            'birthday': date(1986, 6, 15)
        }
        age = calculate_age_at_wedding(person)
        self.assertEqual(age, 25)

        person = {
            'anniversary': date(1969, 8, 21),
            'birthday': date(1945, 6, 15)
        }
        age = calculate_age_at_wedding(person)
        self.assertEqual(age, 24) 
    
    def test_falure_case(self):
        # 故意测试失败
        person = {
            'anniversary': date(1969, 8, 21),
            'birthday': date(1945, 6, 15)
        } 
        age = calculate_age_at_wedding(person)
        self.assertEqual(age, 99)
    
    def test_error_case(self):
        # 故意测试错误
        person = {} 
        age = calculate_age_at_wedding(person)
        self.assertEqual(age, 24) 

    # 特定情况下跳过的测试，使用skipIf与skipUnless装饰器，接受一个表达式
    # skipIf装饰器会导致如果表达式为True时跳过测试
    # skipUnless装饰器在表达式为False时跳过测试
    # 被跳过的测试对应的输出结果是s
    @unittest.skipIf(True, 'This test was skipped.')
    def test_skipped_case(self):
        pass       
```

### 模拟外部测试

模拟是在测试中声明特定函数调用给出一个特定输出的过程，而函数调用本身会被禁止，还可以以特定方式来断言所期望的模拟调用

从python3.3开始，unittest模块发行了unittest.mock，包含了用于模拟的工具，若是在3.2及以前，可以使用mock包

mock模块本质上是一个打补丁的库。它临时将给定命名空间的一个变量替换为一个名为MagicMock的特殊对象，然后在模拟范围结束后将变量还原为之前的值。MagicMock对象本身非常自由，基本上接受(并追踪)对其的任何调用，并返回任何让它返回的值

实际代码

```python
def calculate_age_at_wedding(person_id):
    """根据一个人的结婚日期确定其年龄"""
    # 从数据库中获取个人信息
    person = get_person_from_db(peoson_id)
    anniversary = person['anniversay']
    birthday = person['birthday']
    # 计算年龄
    age = anniversary.year - birthday.year
    # 
    if birthday.replace(year=anniversary.year) > anniversary:
        age -= 1
    return age
```

测试代码

```python
import unittest
import sys
from datetime import date

# 导入mock
try:
    from unittest import mock
except ImportError:
    import mock


class Tests(unittest.TestCase):
    def test_calculate_age_at_wedding(self):
        # 由于模拟的是当前模型中的一个名字，而不是导入模型，需要将模型发送给mock.patch.object
        # mock.patch.object方法作为一个上下文管理器或一个装饰器使用，
        # 接受两个必要参数：被模拟的可调用对象所在的模块，及字符串类型的被调用对象的名称
        # 由于本例中函数及测试在同一文件，必须获得一个对当前模块的引用sys.modules[__name__]
        module = sys.modules[__name__]
        with mock.patch.object(module, 'get_person_from_db') as m:
            # 确保get_person_from_db函数返回有效的字典
            # 若没有设置return_value，则返回另一个MagicMock对象
            m.return_value = {
               'anniversary': date(2012, 4, 21),
                'birthday': date(1986, 6, 15) 
            }
            age = calculate_age_at_wedding(person_id=42)
            self.assertEqual(age, 25)

            # 断言函数get_person_from_db被执行了
            # asssert_called_once_with函数断言两件事：MagicMock被调用且只被调用一次，并且使用了指定的参数签名
            m.asssert_called_once_with(42)
```

检查模拟

```python
# 调用次数与状态
from unittest import mock
m = mock.MagicMock()
m.called  # False，在MagicMock第一次被调用时将called属性设置为True
m.call_count  # 0, MagicMock别调用的次数
m(foo='bar')
m.called. # True
m.call_count  # 1

# 多次调用
# 断言对MagicMock多次调用的组合，提供了assert_has_calls
# assert_has_calls接受一个call对象列表(或其他类似对象，如tuple)，还接受一个可选的关键字参数any_order,默认False，表示期望调用书序与列表中的顺序保持一致。若设置为True，则只需对MagicMock方法进行相同的调用即可，不必关心对该方法的调用顺序
from unittest.mock import call
a = call(42)  # 每次发起对MagicMock对象的调用，都会在内部创建一个存储调用签名(并将其附加到对象内的mock_calls列表)的call对象。若签名匹配，则认为call对象相等
b = call(42)
c = call('foo')
a is b  # False
a == b  # True
a == c  # False

from unittest.mock import MagicMock, call
m = MagicMock()
m.call('a')
m.call('b')
m.call('c')
m.call('d')
m.assert_has_calls([m.call('b'), m.call('c')])
```

检查调用

```python
# 很难检查是否包含某个特定参数，但是查看调用对象自身以及发送给它的参数是可能的
# call类实际上是tuple的子类，并且调用对象是包含三个元素的元组，第二个和第三个参数是调用签名
from unittest.mock import call
c = call('foo', 'bar', spam='eggs')
c[1]  # ('foo', 'bar'), 位置参数的元组
c[2]  # {'spam': 'eggs'}，关键字参数的字典
assert 'bar' in c[1]  # True
assert c[2]['spam'] == 'eggs'  # True
assert 'baz' in c[1]  # 抛错
```

## 运行单元测试

- 方法一：

`mydict_test.py`的最后加上两行代码：

```python
if __name__ == '__main__':
    unittest.main()
```

- 方法二：

在命令行通过参数`-m unittest`直接运行单元测试：

```python
python -m unittest mydict_test
```

推荐的做法，因为这样可以一次批量运行很多单元测试，并且，有很多工具可以自动来运行这些单元测试。

# 覆盖测试

覆盖测试通过代码分析工具和跟踪钩子来判断哪些代码可执行以及哪些代码被执行了，是对单元测试的有效补充，可以用来判断测试的有效性

## coverage

python扩展库coverage可以实现对python代码的覆盖测试

安装

```
pip isntall coverage
```

使用

```
coverage run file.py
```

测试报告

```
coverage report  # 直接查看测试报告
coverage html  # 生成HTML文件的测试报告，保存在htmlcov文件夹中
```

帮助

```
coverage help
```

## 编写覆盖测试

- 手动测试

> 程序代码

```python
# isPrime.py
from random import randint

def isPrime(n):
    for i in range(2, int(n**0.5)+1):
        if n%i == 0:
            return 'No'
    else:
        return 'Yes'
    
n = randint(3, 2000)
print(n,':',isPrime(n))
```

> 测试

```
coverage run isPrime.py  # 执行测试
coverage report  #查看测试报告
coverage report -m  # 显示没有被执行到的代码行号
coverage report -h  # 查看更多选项
```

- 自动测试

使用扩展库coverage的标称接口，可自动生成测试报告

```python
import coverage
from random import randint

cov = coverage.Coverage()
cov.stat()

def isPrime(n):
    for i in range(2, int(n**0.5)+1):
        if n%i == 0:
            return 'No'
    else:
        return 'Yes'
    
n = randint(3, 2000)
print(n,':',isPrime(n))

cov.stop()
cov.save()
cov.html_report()
```

# 性能测试

## time/timeit

使用time和timeit提供的函数来测试代码运行的时间

之外，还可以使用如下方法

```python
from time import time

class Timer(object):
    def __enter__(self):
        self.start = time()
        return self
    
    def __exit__(self):
        self.end = time()
        self.seconds = self.end-self.start
        
def isPrime(n):
    if n == 2:
        return True
   	for i in range(2, int(n**0.5)+2):
        if n%i == 0:
            return False
    return True

with Timer() as t:
    for i in range(1000):
        isPrime(999999999999999999999999)
print(t.seconds)
```

## memory_profiler

扩展库memeory_profiler可以检测代码运行过程中的内存占用情况

```python
from  memory_profiler import profile

@profile
def isPrime(n):
    if n == 2:
        return True
   	for i in range(2, int(n**0.5)+2):
        if n%i == 0:
            return False
    return True

isPrime(999999999999999999)
```

## cProfile

标准库cProfile可以对程序进行测试，给出统计信息，包括代码的执行次数、运行时间等

```python
>>>def fac(n):
    assert isinstance(n ,int) and n >= 0
    if n in (0, 1):
        return 1
    time.sleep(0.1)
    return n * fanc(n-1)
>>>import time
>>>cProfile.run('fac(30)')
```

测试结果说明

| 名称                      | 说明                                               |
| ------------------------- | -------------------------------------------------- |
| ncalls                    | 调用次数                                           |
| tottime                   | 该函数执行所用的总时间，不包括调用子函数所用的时间 |
| percall                   | 该函数单次执行所用的时间                           |
| cumtime                   | 该函数及其所有子函数执行所用的总时间               |
| percall                   | 该函数及其所有子函数单次执行所用的时间             |
| filename:lineno(function) | 函数或代码有关信息                                 |



# 文档测试

如果你经常阅读Python的官方文档，可以看到很多文档都有示例代码。比如[re模块](https://docs.python.org/3/library/re.html)就带了很多示例代码：

```
>>> import re
>>> m = re.search('(?<=abc)def', 'abcdef')
>>> m.group(0)
'def'
```

Python内置的“文档测试”（doctest）模块可以直接提取注释中的代码并执行测试。

doctest严格按照Python交互式命令行的输入和输出来判断测试结果是否正确。只有测试异常的时候，可以用`...`表示中间一大段烦人的输出。

## 测试文档

```
# mydict2.py
class Dict(dict):
    '''
    Simple dict but also support access as x.y style.

    >>> d1 = Dict()
    >>> d1['x'] = 100
    >>> d1.x
    100
    >>> d1.y = 200
    >>> d1['y']
    200
    >>> d2 = Dict(a=1, b=2, c='3')
    >>> d2.c
    '3'
    >>> d2['empty']
    Traceback (most recent call last):
        ...
    KeyError: 'empty'
    >>> d2.empty
    Traceback (most recent call last):
        ...
    AttributeError: 'Dict' object has no attribute 'empty'
    '''
    def __init__(self, **kw):
        super(Dict, self).__init__(**kw)

    def __getattr__(self, key):
        try:
            return self[key]
        except KeyError:
            raise AttributeError(r"'Dict' object has no attribute '%s'" % key)

    def __setattr__(self, key, value):
        self[key] = value

if __name__=='__main__':
    import doctest
    doctest.testmod()
```

## 运行文档

```
python mydict2.py
```

什么输出也没有。这说明我们编写的doctest运行都是正确的。如果程序有问题，运行就会报错



